language: node_js

node_js:
  - "node"

env:
  global:
    - CC_TEST_REPORTER_ID=d1a73cc75bfce4ada1d48ab0f69323e66b483bb010526946a0dc6d45485588cd

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
